export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCHED_PRODUCTS = "FETCHED_PRODUCTS";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCHED_PRODUCT = "FETCHED_PRODUCT";
export const ADD_ITEMS_TO_CART = "ADD_ITEMS_TO_CART";

// Add to Cart
export const FETCH_ADD_TO_CART = "FETCH_ADD_TO_CART";
export const FETCHED_ADD_TO_CART = "FETCHED_ADD_TO_CART";
export const DELETE_CART_ITEM = "DELETE_CART_ITEM";
export const ADD_ITEMS_TO_CART_SUCCESS = "ADD_ITEMS_TO_CART_SUCCESS";

// User Login
export const FETCH_LOGIN = "FETCH_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_USER = "LOGOUT_USER";
export const LOGIN_SESSION = "LOGIN_SESSION";

// Register NEw USer
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_FAILED = "REGISTER_USER_FAILED";
export const CLEAR_REGISTRATION_DATA = "CLEAR_REGISTRATION_DATA";

// USer Profile
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";
export const FETCH_PROFILE = "FETCH_PROFILE";
export const FETCH_PROFILE_SUCCESS = "FETCH_PROFILE_SUCCESS";
export const RETRIVE_ORDER = "RETRIVE_ORDER";
export const RETRIVE_ORDER_SUCCESS = "RETRIVE_ORDER_SUCCESS";
export const RETRIVE_ORDER_FAILED = "RETRIVE_ORDER_FAILED";

//Shipping Page
export const SAVE_SHIPPING_ADDRESS = "SAVE_SHIPPING_ADDRESS";
export const SAVE_SHIPPING_ADDRESS_SUCCESS = "SAVE_SHIPPING_ADDRESS_SUCCESS";
export const SAVE_SHIPPING_ADDRESS_FAILED = "SAVE_SHIPPING_ADDRESS_FAILED";

//Payment page
export const SAVE_PAYMENT_TYPE = "SAVE_PAYMENT_TYPE";
export const SAVE_PAYMENT_TYPE_SUCCESS = "SAVE_PAYMENT_TYPE_SUCCESS";
export const SAVE_PAYMENT_TYPE_FAILED = "SAVE_PAYMENT_TYPE_FAILED";

//Common Actions
export const NAVIGATE_TO_PAGE = "NAVIGATE_TO_PAGE";
export const REQUEST_PAYPAL_SECRET_KEY = "REQUEST_PAYPAL_SECRET_KEY";
export const REQUEST_PAYPAL_SECRET_KEY_SUCEESS =
  "REQUEST_PAYPAL_SECRET_KEY_SUCEESS";

//Place Order Screen
export const PLACE_ORDER = "PLACE_ORDER";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const PLACE_ORDER_FAILED = "PLACE_ORDER_FAILED";

//Order Actions
export const PAY_ORDER = "PAY_ORDER";
export const PAY_ORDER_SUCCESS = "PAY_ORDER_SUCCESS";
export const PAY_ORDER_FAILED = "PAY_ORDER_FAILED";
export const GET_ORDER_DETAILS = "GET_ORDER_DETAILS";
export const GET_ORDER_DETAILS_SUCCESS = "GET_ORDER_DETAILS_SUCCESS";
export const GET_ORDER_DETAILS_FAILED = "GET_ORDER_DETAILS_FAILED";
export const PAY_ORDER_RESET = "PAY_ORDER_RESET";
