export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const FETCHED_PRODUCTS = "FETCHED_PRODUCTS";

export const FETCH_PRODUCT = "FETCH_PRODUCT";
export const FETCHED_PRODUCT = "FETCHED_PRODUCT";
export const ADD_ITEMS_TO_CART='ADD_ITEMS_TO_CART'

// Add to Cart
export const FETCH_ADD_TO_CART = "FETCH_ADD_TO_CART";
export const FETCHED_ADD_TO_CART = "FETCHED_ADD_TO_CART";
export const DELETE_CART_ITEM="DELETE_CART_ITEM"
export const ADD_ITEMS_TO_CART_SUCCESS='ADD_ITEMS_TO_CART_SUCCESS'

// User Login
export const FETCH_LOGIN = "FETCH_LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED="LOGIN_FAILED"

